name: chart-streams
on:
  push:
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    environment:
      name: build
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16.8'
      - run: ./hack/ubuntu/libgit2.sh
        name: "Install libgit2 from sources"
      - run: make CODECOV_TOKEN="$CODECOV_TOKEN" test codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}