name: chart-streams
on:
  push:
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    environment:
      name: build
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/cache@v2
        id: cache-libgit2
        with:
          path: /opt/libgit2
          key: ${{ runner.os }}-${{ hashFiles('hack/ubuntu/libgit2.sh') }}

      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16.8'

      - name: "Install libgit2 from sources"
        run: sudo -E make libgit2
        env:
          LIBGIT_PREFIX: /opt/libgit2
        if: steps.cache-libgit2.outputs.cache-hit != 'true'

      - run: make test
        env:
          PKG_CONFIG_PATH: /opt/libgit2/lib/pkgconfig
          LD_LIBRARY_PATH: /opt/libgit2/lib

      - uses: codecov/codecov-action@v2
        with:
          verbose: true
