name: chart-streams
on:
  push:
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    environment:
      name: build
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/cache@v2
        id: cache-libgit2
        with:
          path: /opt/local/lib/libgit2.so.*
          key: ${{ runner.os }}-libgit2-1.2.0

      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16.8'

      - name: "Install libgit2 from sources"
        run: ./hack/ubuntu/libgit2.sh
        env:
          LIBGIT_PREFIX: /opt/local
        if: steps.cache-libgit2.outputs.cache-hit != 'true'

      - uses: golangci/golangci-lint-action@v2

      - run: make test

      - uses: codecov/codecov-action@v2
        with:
          verbose: true
