name: chart-streams
on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
        with:
          driver-opts: network=host
          install: true
      - uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          file: Dockerfile.dev
          tags: ghcr.io/isutton/chart-streams-dev:latest
      - run: make devcontainer-run IMAGE_DEV_TAG="ghcr.io/isutton/chart-streams-dev:latest" DEVCONTAINER_ARGS="make CODECOV_TOKEN='${CODECOV_TOKEN}' build test codecov"
        env:
          CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}