name: chart-streams
on:
  push:
  pull_request:
    branches:
      - master

env:
  REGISTRY: localhost:5000
  IMAGE_NAME: ${{ github.repository }}
  IMAGE_DEV_TAG: localhost:5000/${{ github.repository }}:${{ github.sha }}

jobs:
  build-and-test:
    environment:
      name: build
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
        with:
          driver-opts: network=host
          install: true
          driver-opts: network=host
      - uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          file: Dockerfile.dev
          tags: ${{ env.IMAGE_DEV_TAG }}
      - run: make devcontainer-run CODECOV_TOKEN="$CODECOV_TOKEN" IMAGE_DEV_TAG="$IMAGE_DEV_TAG" DEVCONTAINER_ARGS="make CODECOV_TOKEN=\"$CODECOV_TOKEN\" test codecov"
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
