name: chart-streams
on: [push]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  IMAGE_DEV_TAG: ghcr.io/${{ github.repository }}:${{ github.sha }}

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
      - uses: actions/checkout@v2

      # https://docs.github.com/en/packages/managing-github-packages-using-github-actions-workflows/publishing-and-installing-a-package-with-github-actions
      - uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-buildx-action@v1
        with:
          driver-opts: network=host
          install: true
      - uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          file: Dockerfile.dev
          tags: ${{ env.IMAGE_DEV_TAG }}
      - run: make devcontainer-run IMAGE_DEV_TAG="$IMAGE_DEV_TAG" DEVCONTAINER_ARGS="make build test codecov"
        env:
          GITHUB_SHA: ${{ github.sha }}
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}