name: chart-streams
on:
  push:
  pull_request:
    branches:
      - master


env:
  REGISTRY: localhost:5000
  IMAGE_NAME: ${{ github.repository }}
  IMAGE_DEV_TAG: localhost:5000/${{ github.repository }}:${{ github.sha }}

jobs:
  build-and-test:
    environment:
      name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # https://docs.github.com/en/packages/managing-github-packages-using-github-actions-workflows/publishing-and-installing-a-package-with-github-actions
      - uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-buildx-action@v1
        with:
          install: true
          driver-opts: network=host
      - uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          file: Dockerfile.dev
          tags: ${{ env.IMAGE_DEV_TAG }}
      - run: make devcontainer-run CODECOV_TOKEN="$CODECOV_TOKEN" IMAGE_DEV_TAG="$IMAGE_DEV_TAG" DEVCONTAINER_ARGS="make CODECOV_TOKEN=\"$CODECOV_TOKEN\" vendor test codecov"
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
